# Site settings
author: Eyamba Ita
title: The 28th Amendment
header-img: img/home-bg.png
email: eyambaita@gmail.com
copyright_name: Eyamba Ita
description: > # this means to ignore newlines until "baseurl:"
  The right to bear and control The Machine 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eyambaita

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
